#!/usr/bin/env bash

SCRIPT_DIR=$(cd $(dirname $0); pwd -P)
ROOT_DIR=$(cd "${SCRIPT_DIR}/../.."; pwd -P)

function prop {
    grep "${1}" "${2}" | cut -d '=' -f2
}

source ${SCRIPT_DIR}/../settings/environment.tfvars

RESOURCE_GROUP="${resource_group_name}"
if [[ -z "${RESOURCE_GROUP}" ]]; then
  echo "resource_group_name is required in environment.tfvars"
  exit 1
fi

REGION="${vlan_region}"
if [[ -z "${REGION}" ]]; then
  echo "vlan_region is required in environment.tfvars"
  exit 1
fi

APIKEY="${IBMCLOUD_API_KEY}"
if [[ -z "${APIKEY}" ]]; then
  if [[ -f ${ROOT_DIR}/credentials.properties ]]; then
    APIKEY=$(prop 'ibmcloud.api.key' "${ROOT_DIR}/credentials.properties")
  else
    echo "${ROOT_DIR}/credentials.properties not found"
  fi
fi

if [[ -z "${APIKEY}" ]]; then
  echo "APIKEY is required either as IBMCLOUD_API_KEY environment variable or in credentials.properties"
  exit 1
fi

if [[ -z "${TMP_DIR}" ]]; then
  TMP_DIR="./.tmp"
fi

mkdir -p "${TMP_DIR}"

ibmcloud config --check-version=false 1> /dev/null 2> /dev/null

echo "Logging into ibmcloud: ${REGION}/${RESOURCE_GROUP}"
ibmcloud login \
  --apikey ${APIKEY} \
  -g ${RESOURCE_GROUP} \
  -r ${REGION} 1> /dev/null 2> /dev/null
