- name: Setting LogDNA Ingestion Key
  shell: "logdna-agent -k {{ conf_key }}"
  when: conf_key != ""

- name: Adding Log Directories
  shell: "logdna-agent -d {{ conf_logdir }}"
  when: conf_logdir != ""

- name: Adding API Host
  shell: "logdna-agent -s LOGDNA_APIHOST={{ ubuntu_api_host }}"
  when: ubuntu_api_host != ""

- name: Adding Log Host
  shell: "logdna-agent -s LOGDNA_LOGHOST={{ ubuntu_log_host }}"
  when: ubuntu_log_host != ""

- name: Setting Tags for This Host
  shell: "logdna-agent -t {{ conf_tags }}"
  when: conf_tags != ""
