- name: Activating LogDNA Agent Service
  shell: "update-rc.d logdna-agent defaults"

- name: Start LogDNA agent
  service:
    name: logdna-agent
    enabled: true
    state: "{{ agent_service }}"
  when: (conf_key != "" and agent_service) or agent_service == "stopped"

- debug:
    msg: "LogDNA Agent has {{ agent_service }}!"
  when: (conf_key != "" and agent_service) or agent_service == "stopped"
